WebUI/Controllers/ChefController.cs
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Dto;
using Omu.ProDinner.WebUI.Mappers;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class ChefController : Cruder<Chef, ChefInput>
    {
        public ChefController(ICrudService<Chef> service, IMapper<Chef, ChefInput> v)
            : base(service, v)
        {
        }

        protected override string RowViewName
        {
            get { return "ListItems/Chef"; }
        }
    }
}

WebUI/Controllers/CountryController.cs
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Dto;
using Omu.ProDinner.WebUI.Mappers;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class CountryController : Cruder<Country, CountryInput>
    {
        public CountryController(ICrudService<Country> service, IMapper<Country, CountryInput> v)
            : base(service, v)
        {
        }

        protected override string RowViewName
        {
            get { return "ListItems/Country"; }
        }
    }
}

WebUI/Controllers/FeedbackController.cs
using System.Web.Mvc;

using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Repository;
using Omu.ProDinner.WebUI.Dto;
using Omu.ValueInjecter;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IRepo<Feedback> repo;

        public FeedbackController(IRepo<Feedback> repo)
        {
            this.repo = repo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new FeedbackInput());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FeedbackInput input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            input.Comments = HtmlUtil.SanitizeHtml(input.Comments);
            
            var feedback = new Feedback { Comments = input.Comments };
            feedback = repo.Insert(feedback);
            repo.Save();

            Session["lastFeedback"] = feedback.Id;
            return Json(new { });
        }

        public ActionResult Edit(int id)
        {
            return View("Create", new FeedbackInput().InjectFrom(repo.Get(id)));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FeedbackInput input)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", input);
            }

            var feedback = repo.Get(input.Id);
            feedback.Comments = HtmlUtil.SanitizeHtml(input.Comments);
            repo.Save();

            return Json(new { });
        }
    }
}

WebUI/Controllers/MealController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Dto;
using Omu.ProDinner.WebUI.Mappers;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class MealController : Cruder<Meal, MealInput>
    {
        private new readonly IMealService service;
        private readonly IFileManagerService fileManagerService;

        public MealController(IMealService service, IMapper<Meal, MealInput> v, IFileManagerService fileManagerService)
            : base(service, v)
        {
            this.service = service;
            this.fileManagerService = fileManagerService;
        }

        public override ActionResult Index()
        {
            return View();
        }

        protected override string RowViewName
        {
            get { return "ListItems/Meal"; }
        }
        
        public ActionResult GetMeal(int id)
        {
            return Json(new { Id = id, Content = this.RenderView(RowViewName, new[] { service.Get(id) }), Type = "meal" });
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            int w, h;
            var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
            return Json(new {name, type = file.ContentType, size = file.ContentLength, w, h});
        }

        public ActionResult ChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult Crop(int x, int y, int w, int h, string filename, int id)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return Json(new {name = filename});
        }

        #region used only by internet explorer and opera (in header.ascx .cool and .notcool from rows are hidden/showed)

        public ActionResult OChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult OChangePicture()
        {
            var file = Request.Files["fileUpload"];
            var id = Convert.ToInt32(Request.Form["id"]);

            if (file.ContentLength > 0)
            {
                int w, h;
                var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
                return RedirectToAction("ocrop",
                                        new CropInput {ImageWidth = w, ImageHeight = h, Id = id, FileName = name});
            }

            return RedirectToAction("Index");
        }

        public ActionResult OCrop(CropInput cropDisplay)
        {
            return View(cropDisplay);
        }

        [HttpPost]
        public ActionResult OCrop(int x, int y, int w, int h, int id, string filename)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return RedirectToAction("ochangepicture", new {id});
        }

        #endregion
        
    }
}

WebUI/Controllers/UserController.cs
using System.Web.Mvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Dto;
using Omu.ProDinner.WebUI.Mappers;

namespace Omu.ProDinner.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Crudere<User, UserCreateInput, UserEditInput>
    {
        private new readonly IUserService service;

        public UserController(IMapper<User, UserCreateInput> v, IMapper<User, UserEditInput> ve, IUserService service) : base(service, v, ve)
        {
            this.service = service;
        }

        public ActionResult ChangePassword(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordInput input)
        {
            if (!ModelState.IsValid) return View(input);
            service.ChangePassword(input.Id, input.Password);
            return Json(new{ Login = service.Get(input.Id).Login});
        }

        protected override string RowViewName
        {
            get { return "ListItems/User"; }
        }
    }
}

WebUI/Views/Shared/ListItems/Chef.cshtml
@model IEnumerable<Chef>
@foreach (var o in Model)
{
    <tr data-val="@o.Id" class="awe-li" id="chef@(o.Id)">
        <td>@o.FirstName @o.LastName
        </td>
        <td>@(o.Country != null ? o.Country.Name : "")
        </td>
        <td>
            <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Url(Url.Action("Edit", "Chef", new { o.Id })).Success("edit").Height(300))">
                <span class="ico-edit"></span>
            </button>
        </td>
        <td>
@Html.Partial("deletebtn", new DelBtn{ Id = o.Id, IsDeleted = o.IsDeleted, Controller = "Chef" })
        </td>
    </tr>               
}

WebUI/Views/Shared/ListItems/ChefThead.cshtml
<tr><th>Name</th><th style="width:45%;">Country</th><th style="width:30px;"></th><th style="width: 30px;"></th></tr>

WebUI/Views/Shared/ListItems/Country.cshtml
@model IEnumerable<Country>
@foreach (var o in Model)
{
    <li data-val="@o.Id" class="awe-li" id="country@(o.Id)">
    <div class="fl">@o.Name</div>
        <div class="fr">
            <div class="act">
                <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Name("editCountry").Url(Url.Action("Edit","Country",new {o.Id})).Success("edit").Height(200))">
                    <span class="ico-edit"></span>
                </button>
                &nbsp;
            @Html.Partial("deletebtn", new DelBtn{ Id = o.Id, IsDeleted = o.IsDeleted, Controller = "Country" })
            </div>
        </div>
    </li>               
}

WebUI/Views/Shared/ListItems/Dinner.cshtml
@model IEnumerable<Dinner>
@foreach (var o in Model)
{
    <li id='dinner@(o.Id)' class="awe-li dinner" data-val="@o.Id">
<div class="fr">    
@Html.Partial("deletebtn", new DelBtn { Id = o.Id, IsDeleted = o.IsDeleted, Controller = "Dinner" })
    </div>
    <div class="fl">
        @o.Name</div>
    <div class="fr">
        @o.Chef.FirstName
        @o.Chef.LastName
        @Mui.from
        @o.Chef.Country.Name
        @Mui.is_cooking&nbsp;</div>
        
    <br class="cbt" />
    @foreach (var m in o.Meals)
    {
        <img src='@Url.Content("~/pictures/Meals/s" + (m.Picture ?? "0.jpg"))' class="sthumb" alt='@m.Name' />
    }
    <br class="cbt" />    
    <div class="fl">
        @o.Country.Name,
        @o.Address</div>        
        <div class="fr">
            <button type="button" class="awe-btn" onclick="@(Url.Awe().PopupFormAction()
                                                   .Url(Url.Action("Edit","Home", new{o.Id}))
                                                   .Success("edit").Modal(true)
                                                   .Fullscreen(true))">
                <span class=" ico-edit"></span>
            </button>
        </div>    
    <div class="fr" style="padding: 0.5em; margin-right: 1em;">
       @Mui.Start @o.Start @Mui.End @o.End </div> 
    <br class="cbt" />    
</li>
}

WebUI/Views/Shared/ListItems/Feedback.cshtml
@model IEnumerable<Feedback>
@{
    var id = 0;
    if(Session["lastFeedback"] != null)
    {
        id = (int)Session["lastFeedback"];
    }
}

@foreach (var o in Model)
{
    <li class="awe-li" data-val="@o.Id">
        <div>
            @Html.Raw(o.Comments)
        </div>
        <div class="fr">
            @{ if(id == o.Id)
               {
        <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction()
        .Url(Url.Action("Edit", "Feedback", new { o.Id }))
        .Success("reload").Height(500).Width(900))">
                Edit</button> 
               }
            }
        </div>
    </li>
} 

WebUI/Views/Shared/ListItems/Meal.cshtml
@model IEnumerable<Meal>
@foreach (var o in Model)
{
    <li id='meal@(o.Id)' class="awe-li meal awe-il" data-val="@o.Id">
        <div>@o.Name
            <div class="fr">
                @Html.Partial("deletebtn", new DelBtn { Id = o.Id, IsDeleted = o.IsDeleted, Controller = "Meal" })
            </div>
        </div>
        <div>
            <div class="fl">
                <img  src='@Url.Content("~/pictures/Meals/" + (string.IsNullOrEmpty(o.Picture) ? "0.jpg" : o.Picture))' class="thumb"  alt='picture' /></div>
            <div class="comments">@o.Comments</div>
            <br class="cbt" />
        </div>
        <div class="cbt" style="margin-top: 0.5em;">
            <div class='cool fl'>
                <button type="button" class="awe-btn" onclick="@(Url.Awe().PopupAction().Url(Url.Action("ChangePicture", "Meal", new { o.Id })).Fullscreen(true).RemoveOnClose(false))" style="padding:0.1em 0.3em">@Mui.change_picture</button>
            </div>
            <div class='notcool fl'>                
                <button type="button" class="awe-btn" onclick="location.href='@Url.Action("ochangepicture", "Meal", new { o.Id })'">@Mui.change_picture</button>
            </div>
            <div class="fr">
                <button type="button" class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Name("EditMealPopup").Url(Url.Action("Edit", "Meal", new { o.Id })).Success("edit"))" style="padding:0.1em 0.3em">
                    <span class="ico-edit"></span>
                </button>
            </div>
        </div>
    </li>
}

WebUI/Views/Shared/ListItems/MealItem.cshtml
@model IEnumerable<Meal>
@foreach (var o in Model)
{
    <li class="awe-li mealitem awe-il" data-val="@o.Id">
        <div>
            <button class="awe-btn awe-movebtn mealmove">
                <span class="awe-icon"></span>
            </button>
            @o.Name
        </div>
        <img  src='@Url.Content("~/pictures/Meals/" + (string.IsNullOrEmpty(o.Picture) ? "0.jpg" : o.Picture))' class="thumb"  alt='picture' />
    </li>
}

WebUI/Views/Shared/ListItems/User.cshtml
@model IEnumerable<User>
@foreach (var o in Model)
{
    <tr id='user@(o.Id)' data-val="@o.Id" class="awe-li">
        <td>
            @o.Login
        </td>
        <td>@(string.Join(",", o.Roles.Select(r => r.Name)))
        </td>
        <td>
            <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Url(Url.Action("Edit", "User", new { o.Id })).Success("edit").Height(300))">
                <span class="ico-edit"></span>

            </button>
        </td>
        <td>
            <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Url(Url.Action("ChangePassword", "User", new { o.Id })).Success("passchanged").Height(200))">
                password</button>            
        </td>
        <td>
            @Html.Partial("deletebtn", new DelBtn{ Id = o.Id, IsDeleted = o.IsDeleted, Controller = "User" })
        </td>
    </tr>
}

WebUI/Views/Shared/ListItems/UserThead.cshtml
<tr><th style="width:200px;">Login</th><th>Roles</th><th style="width:30px;"></th><th style="width: 65px;"></th><th style="width: 30px;"></th></tr>