WebUI/Controllers/MealController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Dto;
using Omu.ProDinner.WebUI.Mappers;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class MealController : Cruder<Meal, MealInput>
    {
        private new readonly IMealService service;
        private readonly IFileManagerService fileManagerService;

        public MealController(IMealService service, IMapper<Meal, MealInput> v, IFileManagerService fileManagerService)
            : base(service, v)
        {
            this.service = service;
            this.fileManagerService = fileManagerService;
        }

        public override ActionResult Index()
        {
            return View();
        }

        protected override string RowViewName
        {
            get { return "ListItems/Meal"; }
        }
        
        public ActionResult GetMeal(int id)
        {
            return Json(new { Id = id, Content = this.RenderView(RowViewName, new[] { service.Get(id) }), Type = "meal" });
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            int w, h;
            var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
            return Json(new {name, type = file.ContentType, size = file.ContentLength, w, h});
        }

        public ActionResult ChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult Crop(int x, int y, int w, int h, string filename, int id)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return Json(new {name = filename});
        }

        #region used only by internet explorer and opera (in header.ascx .cool and .notcool from rows are hidden/showed)

        public ActionResult OChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult OChangePicture()
        {
            var file = Request.Files["fileUpload"];
            var id = Convert.ToInt32(Request.Form["id"]);

            if (file.ContentLength > 0)
            {
                int w, h;
                var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
                return RedirectToAction("ocrop",
                                        new CropInput {ImageWidth = w, ImageHeight = h, Id = id, FileName = name});
            }

            return RedirectToAction("Index");
        }

        public ActionResult OCrop(CropInput cropDisplay)
        {
            return View(cropDisplay);
        }

        [HttpPost]
        public ActionResult OCrop(int x, int y, int w, int h, int id, string filename)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return RedirectToAction("ochangepicture", new {id});
        }

        #endregion
        
    }
}

WebUI/Views/Meal/Create.cshtml
@model MealInput
<div class="mealform">
@using (Html.BeginForm())
{  
    @Html.EditorFor(o => o.Name)            
    @Html.EditorFor(o => o.Comments)
}
</div>

WebUI/Views/Meal/Index.cshtml
@{
    ViewBag.Title = "Meals";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/jquery.fileupload-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/jquery.Jcrop.css")" rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery.fileupload.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.fileupload-ui.js")" type="text/javascript"></script>
<script src='@Url.Content("~/Scripts/jquery.Jcrop.min.js")' type="text/javascript" ></script>

<h2>@Mui.Meals</h2>
<fieldset><legend>@Mui.Search</legend>
    @Html.Awe().TextBox("Search").Placeholder(Mui.Search)
</fieldset>
<br />
<button type="button" class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Name("CreateMealPopup").Url(Url.Action("create")).Success("createMeal").Height(330))">
        @Mui.Create</button>
@Html.Awe().AjaxList("Meals").Parent("Search", "search").CssClass("mealslist")

@Html.Awe().Form().FormClass("MealRestore").Success("edit").Url(Url.Action("Restore"))
@Html.Awe().Form().Confirm(true).FormClass("MealConfirm").Success("del").Url(Url.Action("Delete"))
<script type="text/javascript">
    function updateMeal(id) {
        $.post('@Url.Action("GetMeal")', { id: id }, edit);
    }

    $(function () {
        $(document).ajaxComplete(adjustMeals);
        $(window).resize(adjustMeals);
    });
</script>

WebUI/Views/Meal/ochangepicture.cshtml
@model Meal
@{
    ViewBag.Title = "Picture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    @Mui.Picture @Model.Name</h2>

 <img  src='@Url.Content("~/pictures/Meals/"+Model.Picture)'  alt='picture' />
@using (Html.BeginForm("ochangepicture", "Meal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{     
    <input type="hidden" id="id" name="id" value="@Model.Id" />
    <input type="file" id="fileUpload" name="fileUpload" />
    <input type="submit" value="@Mui.upload_file" />   
}

WebUI/Views/Meal/ocrop.cshtml
@model CropInput
@{
    ViewBag.Title = "Picture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/jquery.Jcrop.css")" rel="stylesheet" type="text/css" />
<script src='@Url.Content("~/Scripts/jquery.Jcrop.min.js")' type="text/javascript" ></script>

<script language="Javascript" type="text/javascript">

        $(function() {
            $('#cropbox').Jcrop({
                setSelect: [ 0, 0, 200, 150 ],
                onChange: showPreview,
                onSelect: showPreview,
                aspectRatio: 1.333
            });
        });
        
         function updateCoords(c) {
		        $('#x').val(c.x);
		        $('#y').val(c.y);
		        $('#w').val(c.w);
		        $('#h').val(c.h);
		    }

        function showPreview(coords) {
        updateCoords(coords);
        
            if (parseInt(coords.w) > 0) {
                var rx = 200 / coords.w;
                var ry = 150 / coords.h;

                $('#preview').css({
                    width: Math.round(rx * @Model.ImageWidth) + 'px',
                    height: Math.round(ry * @Model.ImageHeight) + 'px',
                    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                    marginTop: '-' + Math.round(ry * coords.y) + 'px'
                });
            }
        }		
</script>
<div style="margin: auto; width: 900px;">
    <div style="float: left;">
        <img src='@Url.Content("~/pictures/temp/" + Model.FileName)' id="cropbox" alt="crop" />
    </div>
    <div style="width: 200px; height: 150px; overflow: hidden; float: right;">
        <img src='@Url.Content("~/pictures/temp/" + Model.FileName)' id="preview" alt="thumb" />
    </div>
    <br class="cbt" />
    <br />
    @using (Html.BeginForm())
    {
        <input type="hidden" id="x" name="x" />
        <input type="hidden" id="y" name="y" />
        <input type="hidden" id="w" name="w" />
        <input type="hidden" id="h" name="h" />
        <input type="hidden" id="filename" name="@Model.FileName" />
        <input type="hidden" id="id" name="@Model.Id" />
        <input type="submit" value="@Mui.select_thumbnail" />
    }
</div>