WebUI/Controllers/Awesome/ChefGridController.cs
using System.Linq;
using System.Web.Mvc;
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Repository;

namespace Omu.ProDinner.WebUI.Controllers.Awesome
{
    public class ChefGridController : Controller
    {
        private readonly IRepo<Chef> repo;

        public ChefGridController(IRepo<Chef> repo)
        {
            this.repo = repo;
        }

        public ActionResult GetItems(GridParams g, string parent)
        {
            var data = repo.Where(o => o.FirstName.StartsWith(parent) || o.LastName.StartsWith(parent), User.IsInRole("admin"))
                .OrderByDescending(o => o.Id);
            
            return Json(new GridModelBuilder<Chef>(data.AsQueryable(), g)
            {
                Map = chef => new
                {
                    chef.FirstName,
                    chef.LastName,
                    Country = chef.Country.Name,
                    Actions = this.RenderView("ChefGridActions", chef) // view in Shared/ChefGridActions.cshtml
                }
            }.Build());
        }
    }
}

WebUI/Controllers/ChangeThemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class ChangeThemeController : Controller
    {
        private const string DefaultTheme = "bui";

        private const string CookieName = "prodinner81theme";

        //theme, jqueryUiTheme
        readonly IDictionary<string, string> themes = new Dictionary<string, string>
            {
                {"bui", "smoothness"}, 
                {"met", "smoothness"}, 
                {"gui","smoothness"},
                {"gui2", "smoothness"}, 
                {"gui3", "start"},
                {"compact", "smoothness"}, 
                {"start","start"}, 
                {"black-tie","black-tie"}, 
            };

        public ActionResult Index()
        {
            var currentTheme = DefaultTheme;

            if (Request.Cookies[CookieName] != null)
                currentTheme = Request.Cookies[CookieName].Value;

            return View(themes.Select(theme => new SelectListItem
            {
                Text = theme.Key,
                Value = theme.Key + "|" + theme.Value,
                Selected = theme.Key == currentTheme
            }));
        }

        [HttpPost]
        public ActionResult Change(string s)
        {
            Response.Cookies.Add(new HttpCookie(CookieName, s) { Expires = DateTime.Now.AddDays(30) });
            return new EmptyResult();
        }

        public string GetTheme()
        {
            var s = DefaultTheme;
            if (Request.Cookies[CookieName] != null && themes.ContainsKey(Request.Cookies[CookieName].Value))
            {
                s = Request.Cookies[CookieName].Value;
            }

            return s;
        }

        public string GetJqTheme()
        {
            var s = DefaultTheme;
            if (Request.Cookies[CookieName] != null && themes.ContainsKey(Request.Cookies[CookieName].Value))
            {
                s = Request.Cookies[CookieName].Value;
            }

            return themes[s];
        }
    }
}

WebUI/Controllers/ChefController.cs
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Dto;
using Omu.ProDinner.WebUI.Mappers;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class ChefController : Cruder<Chef, ChefInput>
    {
        public ChefController(ICrudService<Chef> service, IMapper<Chef, ChefInput> v)
            : base(service, v)
        {
        }

        protected override string RowViewName
        {
            get { return "ListItems/Chef"; }
        }
    }
}

WebUI/Controllers/NavController.cs
using System.Web.Mvc;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class NavController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebUI/Views/Shared/ChefGridActions.cshtml
@model Chef
<div class="awe-il">
    <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction().Url(Url.Action("Edit", "Chef", new { Model.Id })).Success("refreshChefGrid").Height(300))">
        <span class="ico-edit"></span>
    </button>
</div>&nbsp;
<div class="awe-il">
@Html.Partial("deletebtn", new DelBtn { Id = Model.Id, IsDeleted = Model.IsDeleted, Controller = "Chef" })
</div>

WebUI/Views/Shared/_Layout.cshtml
@using System.Threading
<!DOCTYPE html>
<html>
<head>
    <title>
        @ViewBag.Title
    </title>
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    @*css styles*@
    <link href="@Url.Content("~")Content/themes/@Html.Action("GetTheme", "ChangeTheme")/Site.css?v=81" rel="stylesheet" type="text/css" id="demoStyle" />
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/@Html.Action("GetJqTheme", "ChangeTheme")/jquery-ui.css" rel="stylesheet" id="jqStyle" />
    <link href="@Url.Content("~")Content/themes/@Html.Action("GetTheme", "ChangeTheme")/AwesomeMvc.css?v=81" rel="stylesheet" type="text/css" id="aweStyle" />
    <link href="@Url.Content("~/Content/Common.css")?v=81" rel="stylesheet" type="text/css" />
    @*js scripts*@
    <script src="@Url.Content("~/Scripts/JSON2.js")" type="text/javascript"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.js"></script>
    
     <script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>
    @* jquery-migrate needed for ie8 when using jquery.validate.unobtrusive with jquery 1.9 and higher *@

    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
       <script type="text/javascript" src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <script src="@Url.Content("~/Scripts/AwesomeMvc.js")?v=81" type="text/javascript"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")"></script>

    <script src="@Url.Content("~/Scripts/Site.js")?v=2" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            awe.err = function (xhr, textStatus, errorThrown) {
                var msg = "unexpected error occured";
                if (xhr) {
                    msg = xhr.responseText.replace(".js","").replace(".css","");
                }
                msg += "<hr/> you see this message because in _Layout.cshtml awe.err is set to a function that shows this popup";
                $('<div/>').dialog({ title: 'unexpected error', width: 370, height: 200, position: ["left", "bottom"], dialogClass: "errPopup" }).html(msg);
            };
            
            @*//setting the correct date format for jquery.validate*@
            jQuery.validator.addMethod(
           'date',
           function (value, element, params) {
               if (this.optional(element)) {
                   return true;
               };
               var result = false;
               try {
                   $.datepicker.parseDate('@(JQueryDate.ConvertDateFormat(Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern))', value);
                    result = true;
                } catch (err) {
                    result = false;
                }
                return result;
            },
            ''
        );
            
            var root = '@Url.Content("~")';
            $('#chTheme').change(function () {
                var v = $(this).val().split("|");
                var theme = v[0];
                var jqTheme = v[1];
                $('#jqStyle').attr('href', "http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/" + jqTheme + "/jquery-ui.css");
                $('#aweStyle').attr('href', root + "Content/themes/" + theme + "/AwesomeMvc.css");
                $('#demoStyle').attr('href', root + "Content/themes/" + theme + "/Site.css");
                $.post('@Url.Action("Change", "ChangeTheme")', { s: theme });
            });
        });

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-27119754-1']);
        _gaq.push(['_setDomainName', 'aspnetawesome.com']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>
    <noscript>
        <div id="nos">
            this site works best with javascript allowed
        </div>
    </noscript>
    @Html.Partial("doggy")
    <div id="top-wrapper">
        <div id="header" class="container">
            <div id="hlogo">
                <a href="@Url.Content("~")" id="fun">
                    <img src='@Url.Content("~\\Content\\strawberry.png")' alt="logo" />
                </a>
            </div>
            <div class="hmenus">
                <div class="nav">
                    @Html.Action("Index", "Nav")
                </div>
            </div>
            <div class="trmi">
                @Html.Partial("login")
            </div>
            <div class="trmi">
                @Html.Action("index", "mui")
            </div>
            <div class="trmi">
                @Html.Action("Index", "ChangeTheme")
            </div>
            <div class="trmi"><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2Faspnet-mvc-project-awesome%2F145701755486515&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:103px; height:21px;margin-top:5px;" allowTransparency="true"></iframe></div>
        </div>
        <div class="cbt">
        </div>
    </div>
    <div id="main-container">
        <div id="main" class="maindiv ">
            @RenderBody()
        </div>
    </div>
    <div id="footer">
        <div class="maindiv">
            <span style="margin: 10px; float: right;"><a href="https://twitter.com/share"
                class="twitter-share-button" data-url="http://prodinner.aspnetawesome.com" data-count="none"
                data-hashtags="aspnetawesome">Tweet</a>
                <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = "//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } } (document, "script", "twitter-wjs");</script>
            </span><br/><span><a href='http://prodinner.codeplex.com'>project home: http://prodinner.codeplex.com</a></span>
        </div>
    </div>
</body>
</html>

WebUI/Views/Shared/deletebtn.cshtml
@model DelBtn
@if (Model.IsDeleted)
{
    <form class="@(Model.Controller+"Restore") awe-il" method="post">
        @Html.HiddenFor(o => o.Id)
        <button type="submit" class="awe-btn" >re</button>
    </form>
}
else
{
    <form class="@(Model.Controller+"Confirm") awe-il" method="post">
        @Html.HiddenFor(o => o.Id)
        <button type="submit" class="awe-btn">
            <span class="ico-del"></span>
        </button>
    </form>
}